package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table current_year_table.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class CurrentYearTable extends CurrentYearTable_gen implements java.io.Serializable {

}
