package com.hbaspecto.pecas.sd.orm;
import simpleorm.dataset.*;
import simpleorm.utils.*;
import simpleorm.sessionjdbc.SSessionJdbc;
import java.math.BigDecimal;
import java.util.Date;

/**	Base class of table development_fee_schedules.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Fri Sep 25 16:13:29 MDT 2009
***/
abstract class DevelopmentFeeSchedules_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <DevelopmentFeeSchedules> meta = new SRecordMeta<DevelopmentFeeSchedules>(DevelopmentFeeSchedules.class, "development_fee_schedules");

//Columns in table
   public static final SFieldInteger FeeScheduleId =
      new SFieldInteger(meta, "fee_schedule_id",
         new SFieldFlags[] { SFieldFlags.SPRIMARY_KEY, SFieldFlags.SMANDATORY });

//Column getters and setters
   public int get_FeeScheduleId(){ return getInt(FeeScheduleId);}
   public void set_FeeScheduleId( int value){setInt( FeeScheduleId,value);}

//Find and create
   public static DevelopmentFeeSchedules findOrCreate( SSessionJdbc ses ,int _FeeScheduleId ){
      return ses.findOrCreate(meta, new Object[] {new Integer( _FeeScheduleId)});
   }
   public SRecordMeta <DevelopmentFeeSchedules> getMeta() {
       return meta;
   }
}
