package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table development_fee_schedules.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class DevelopmentFeeSchedules extends DevelopmentFeeSchedules_gen implements java.io.Serializable {

}
