package com.hbaspecto.pecas.sd.orm;
import simpleorm.dataset.*;
import simpleorm.utils.*;
import simpleorm.sessionjdbc.SSessionJdbc;
import java.math.BigDecimal;
import java.util.Date;

import com.hbaspecto.pecas.sd.SpaceTypesI;

/**	Base class of table development_fees.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Fri Sep 25 16:13:29 MDT 2009
***/
abstract class DevelopmentFees_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <DevelopmentFees> meta = new SRecordMeta<DevelopmentFees>(DevelopmentFees.class, "development_fees");

//Columns in table
   public static final SFieldInteger FeeScheduleId =
      new SFieldInteger(meta, "fee_schedule_id",
         new SFieldFlags[] { SFieldFlags.SPRIMARY_KEY, SFieldFlags.SMANDATORY });

   public static final SFieldInteger SpaceTypeId =
      new SFieldInteger(meta, "space_type_id",
         new SFieldFlags[] { SFieldFlags.SPRIMARY_KEY, SFieldFlags.SMANDATORY });

   public static final SFieldDouble DevelopmentFeePerUnitSpaceInitial =
      new SFieldDouble(meta, "development_fee_per_unit_space_initial");

   public static final SFieldDouble DevelopmentFeePerUnitLandInitial =
      new SFieldDouble(meta, "development_fee_per_unit_land_initial");

   public static final SFieldDouble DevelopmentFeePerUnitSpaceOngoing =
      new SFieldDouble(meta, "development_fee_per_unit_space_ongoing");

   public static final SFieldDouble DevelopmentFeePerUnitLandOngoing =
      new SFieldDouble(meta, "development_fee_per_unit_land_ongoing");

//Column getters and setters
   public int get_FeeScheduleId(){ return getInt(FeeScheduleId);}
   public void set_FeeScheduleId( int value){setInt( FeeScheduleId,value);}

   public int get_SpaceTypeId(){ return getInt(SpaceTypeId);}
   public void set_SpaceTypeId( int value){setInt( SpaceTypeId,value);}

   public double get_DevelopmentFeePerUnitSpaceInitial(){ return getDouble(DevelopmentFeePerUnitSpaceInitial);}
   public void set_DevelopmentFeePerUnitSpaceInitial( double value){setDouble( DevelopmentFeePerUnitSpaceInitial,value);}

   public double get_DevelopmentFeePerUnitLandInitial(){ return getDouble(DevelopmentFeePerUnitLandInitial);}
   public void set_DevelopmentFeePerUnitLandInitial( double value){setDouble( DevelopmentFeePerUnitLandInitial,value);}

   public double get_DevelopmentFeePerUnitSpaceOngoing(){ return getDouble(DevelopmentFeePerUnitSpaceOngoing);}
   public void set_DevelopmentFeePerUnitSpaceOngoing( double value){setDouble( DevelopmentFeePerUnitSpaceOngoing,value);}

   public double get_DevelopmentFeePerUnitLandOngoing(){ return getDouble(DevelopmentFeePerUnitLandOngoing);}
   public void set_DevelopmentFeePerUnitLandOngoing( double value){setDouble( DevelopmentFeePerUnitLandOngoing,value);}

//Foreign key getters and setters
   public DevelopmentFeeSchedules get_DEVELOPMENT_FEE_SCHEDULES(SSessionJdbc ses){
     try{
/** Old code: 
        return DevelopmentFeeSchedules.findOrCreate(get_FeeScheduleId());
New code below :**/
        return ses.findOrCreate(DevelopmentFeeSchedules.meta,new Object[]{ 
        	get_FeeScheduleId(),
 });
     } catch (SException e) {
        if (e.getMessage().indexOf("Null Primary key") > 0) {
          return null;
        }
        throw e;
     }
   }
   public void set_DEVELOPMENT_FEE_SCHEDULES( DevelopmentFeeSchedules value){
      set_FeeScheduleId( value.get_FeeScheduleId());
   }

   public SpaceTypesI get_SPACE_TYPES_I(SSessionJdbc ses){
     try{
/** Old code: 
        return SpaceTypesI.findOrCreate(get_SpaceTypeId());
New code below :**/
        return ses.findOrCreate(SpaceTypesI.meta,new Object[]{ 
        	get_SpaceTypeId(),
 });
     } catch (SException e) {
        if (e.getMessage().indexOf("Null Primary key") > 0) {
          return null;
        }
        throw e;
     }
   }
   public void set_SPACE_TYPES_I( SpaceTypesI value){
      set_SpaceTypeId( value.get_SpaceTypeId());
   }

//Find and create
   public static DevelopmentFees findOrCreate( SSessionJdbc ses ,int _FeeScheduleId, int _SpaceTypeId ){
      return ses.findOrCreate(meta, new Object[] {new Integer( _FeeScheduleId), new Integer( _SpaceTypeId)});
   }
   public static DevelopmentFees findOrCreate( SSessionJdbc ses,DevelopmentFeeSchedules _ref, int _SpaceTypeId){
      return findOrCreate( ses, _ref.get_FeeScheduleId(), _SpaceTypeId);
   }

   public static DevelopmentFees findOrCreate( SSessionJdbc ses,SpaceTypesI _ref, int _FeeScheduleId){
      return findOrCreate( ses, _FeeScheduleId, _ref.get_SpaceTypeId());
   }

   public SRecordMeta <DevelopmentFees> getMeta() {
       return meta;
   }
}
