package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table development_fees.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class DevelopmentFees extends DevelopmentFees_gen implements java.io.Serializable {

}
