package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table floorspacei_view.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class FloorspaceiView extends FloorspaceiView_gen implements java.io.Serializable {

}
