package com.hbaspecto.pecas.sd.orm;
import simpleorm.dataset.*;
import simpleorm.utils.*;
import simpleorm.sessionjdbc.SSessionJdbc;
import java.math.BigDecimal;
import java.util.Date;

/**	Base class of table floorspacei_view.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Fri Sep 25 16:13:29 MDT 2009
***/
abstract class FloorspaceiView_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <FloorspaceiView> meta = new SRecordMeta<FloorspaceiView>(FloorspaceiView.class, "floorspacei_view");

//Columns in table
   public static final SFieldInteger Taz =
      new SFieldInteger(meta, "taz");

   public static final SFieldString AaCommodity =
      new SFieldString(meta, "commodity", 2147483647);

   public static final SFieldDouble Quantity =
      new SFieldDouble(meta, "quantity");

//Column getters and setters
   public int get_Taz(){ return getInt(Taz);}
   public void set_Taz( int value){setInt( Taz,value);}

   public String get_AaCommodity(){ return getString(AaCommodity);}
   public void set_AaCommodity( String value){setString( AaCommodity,value);}

   public double get_Quantity(){ return getDouble(Quantity);}
   public void set_Quantity( double value){setDouble( Quantity,value);}

//Find and create
   public static FloorspaceiView findOrCreate( SSessionJdbc ses  ){
      return ses.findOrCreate(meta, new Object[] {});
   }
   public SRecordMeta <FloorspaceiView> getMeta() {
       return meta;
   }
}
