package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table most_recent_local_effect_with_taz.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class MostRecentLocalEffectWithTaz extends MostRecentLocalEffectWithTaz_gen implements java.io.Serializable {

}
