package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table most_recent_zoning_year.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class MostRecentZoningYear extends MostRecentZoningYear_gen implements java.io.Serializable {

}
