package com.hbaspecto.pecas.sd.orm;
import simpleorm.dataset.*;
import simpleorm.utils.*;
import simpleorm.sessionjdbc.SSessionJdbc;
import java.math.BigDecimal;
import java.util.Date;

/**	Base class of table most_recent_zoning_year.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Fri Sep 25 16:13:29 MDT 2009
***/
abstract class MostRecentZoningYear_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <MostRecentZoningYear> meta = new SRecordMeta<MostRecentZoningYear>(MostRecentZoningYear.class, "most_recent_zoning_year");

//Columns in table
   public static final SFieldLong PecasParcelNum =
      new SFieldLong(meta, "pecas_parcel_num");

   public static final SFieldInteger CurrentZoningYear =
      new SFieldInteger(meta, "current_zoning_year");

//Column getters and setters
   public long get_PecasParcelNum(){ return getLong(PecasParcelNum);}
   public void set_PecasParcelNum( long value){setLong( PecasParcelNum,value);}

   public int get_CurrentZoningYear(){ return getInt(CurrentZoningYear);}
   public void set_CurrentZoningYear( int value){setInt( CurrentZoningYear,value);}

//Find and create
   public static MostRecentZoningYear findOrCreate( SSessionJdbc ses  ){
      return ses.findOrCreate(meta, new Object[] {});
   }
   public SRecordMeta <MostRecentZoningYear> getMeta() {
       return meta;
   }
}
