package com.hbaspecto.pecas.sd.orm;
import simpleorm.dataset.*;
import simpleorm.utils.*;
import simpleorm.sessionjdbc.SSessionJdbc;
import java.math.BigDecimal;
import java.util.Date;

/**	Base class of table most_recent_local_effect_year.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Fri Sep 25 16:13:29 MDT 2009
***/
abstract class MostRecentLocalEffectYear_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <MostRecentLocalEffectYear> meta = new SRecordMeta<MostRecentLocalEffectYear>(MostRecentLocalEffectYear.class, "most_recent_local_effect_year");

//Columns in table
   public static final SFieldLong PecasParcelNum =
      new SFieldLong(meta, "pecas_parcel_num");

   public static final SFieldInteger CurrentLocalEffectYear =
      new SFieldInteger(meta, "current_local_effect_year");

//Column getters and setters
   public long get_PecasParcelNum(){ return getLong(PecasParcelNum);}
   public void set_PecasParcelNum( long value){setLong( PecasParcelNum,value);}

   public int get_CurrentLocalEffectYear(){ return getInt(CurrentLocalEffectYear);}
   public void set_CurrentLocalEffectYear( int value){setInt( CurrentLocalEffectYear,value);}

//Find and create
   public static MostRecentLocalEffectYear findOrCreate( SSessionJdbc ses  ){
      return ses.findOrCreate(meta, new Object[] {});
   }
   public SRecordMeta <MostRecentLocalEffectYear> getMeta() {
       return meta;
   }
}
