package com.hbaspecto.pecas.sd.orm;

import simpleorm.sessionjdbc.SSessionJdbc;

import com.hbaspecto.pecas.sd.orm.Parcels_gen;
import com.sun.swing.internal.plaf.metal.resources.metal;

/**Business rules class for table parcels.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class ObservedDevelopmentEvents extends ObservedDevelopmentEvents_gen implements java.io.Serializable{
	
}
