package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table parcel_cost_xref.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class ParcelCostXref extends ParcelCostXref_gen implements java.io.Serializable {

}
