package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table parcel_fee_xref.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class ParcelFeeXref extends ParcelFeeXref_gen implements java.io.Serializable {

}
