package com.hbaspecto.pecas.sd.orm;
import com.hbaspecto.pecas.land.ParcelsTemp;

import simpleorm.dataset.*;
import simpleorm.sessionjdbc.SSessionJdbc;


/**	Base class of table parcels_temp.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Thu Nov 26 14:35:39 MST 2009
***/
public class ParcelsTemp_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <ParcelsTemp> meta = new SRecordMeta<ParcelsTemp>(ParcelsTemp.class, "parcels_temp");

//Columns in table
   public static final SFieldString ParcelId =
      new SFieldString(meta, "parcel_id", 2147483647);

   public static final SFieldLong PecasParcelNum =
      new SFieldLong(meta, "pecas_parcel_num",
         new SFieldFlags[] { SFieldFlags.SPRIMARY_KEY, SFieldFlags.SMANDATORY });

   public static final SFieldInteger YearBuilt =
      new SFieldInteger(meta, "year_built");

   public static final SFieldInteger Taz =
      new SFieldInteger(meta, "taz");

   public static final SFieldInteger SpaceTypeId =
      new SFieldInteger(meta, "space_type_id");

   public static final SFieldDouble SpaceQuantity =
      new SFieldDouble(meta, "space_quantity");

   public static final SFieldDouble LandArea =
      new SFieldDouble(meta, "land_area");

   public static final SFieldInteger AvailableServicesCode =
      new SFieldInteger(meta, "available_services_code");

   public static final SFieldInteger ZoningRulesCode =
      new SFieldInteger(meta, "zoning_rules_code");

   public static final SFieldInteger CostScheduleId =
      new SFieldInteger(meta, "cost_schedule_id");

   public static final SFieldInteger FeeScheduleId =
      new SFieldInteger(meta, "fee_schedule_id");

   public static final SFieldBooleanBit IsDerelict =
      new SFieldBooleanBit(meta, "is_derelict");

   public static final SFieldBooleanBit IsBrownfield =
      new SFieldBooleanBit(meta, "is_brownfield");

   public static final SFieldDouble Randnum =
      new SFieldDouble(meta, "randnum");

//Column getters and setters
   public String get_ParcelId(){ return getString(ParcelId);}
   public void set_ParcelId( String value){setString( ParcelId,value);}

   public long get_PecasParcelNum(){ return getLong(PecasParcelNum);}
   public void set_PecasParcelNum( long value){setLong( PecasParcelNum,value);}

   public int get_YearBuilt(){ return getInt(YearBuilt);}
   public void set_YearBuilt( int value){setInt( YearBuilt,value);}

   public int get_Taz(){ return getInt(Taz);}
   public void set_Taz( int value){setInt( Taz,value);}

   public int get_SpaceTypeId(){ return getInt(SpaceTypeId);}
   public void set_SpaceTypeId( int value){setInt( SpaceTypeId,value);}

   public double get_SpaceQuantity(){ return getDouble(SpaceQuantity);}
   public void set_SpaceQuantity( double value){setDouble( SpaceQuantity,value);}

   public double get_LandArea(){ return getDouble(LandArea);}
   public void set_LandArea( double value){setDouble( LandArea,value);}

   public int get_AvailableServicesCode(){ return getInt(AvailableServicesCode);}
   public void set_AvailableServicesCode( int value){setInt( AvailableServicesCode,value);}

   public int get_ZoningRulesCode(){ return getInt(ZoningRulesCode);}
   public void set_ZoningRulesCode( int value){setInt( ZoningRulesCode,value);}

   public int get_CostScheduleId(){ return getInt(CostScheduleId);}
   public void set_CostScheduleId( int value){setInt( CostScheduleId,value);}

   public int get_FeeScheduleId(){ return getInt(FeeScheduleId);}
   public void set_FeeScheduleId( int value){setInt( FeeScheduleId,value);}

   public boolean get_IsDerelict(){ return getBoolean(IsDerelict);}
   public void set_IsDerelict( boolean value){setBoolean( IsDerelict,value);}

   public boolean get_IsBrownfield(){ return getBoolean(IsBrownfield);}
   public void set_IsBrownfield( boolean value){setBoolean( IsBrownfield,value);}

   public double get_Randnum(){ return getDouble(Randnum);}
   public void set_Randnum( double value){setDouble( Randnum,value);}

//Find and create
   public static ParcelsTemp findOrCreate( SSessionJdbc ses ,long _PecasParcelNum ){
      return ses.findOrCreate(meta, new Object[] {new Long( _PecasParcelNum)});
   }
   public SRecordMeta <ParcelsTemp> getMeta() {
       return meta;
   }
}
