package com.hbaspecto.pecas.sd.orm;
import simpleorm.dataset.*;
import simpleorm.utils.*;
import com.hbaspecto.pecas.sd.SpaceTypesI;
import simpleorm.sessionjdbc.SSessionJdbc;


/**	Base class of table space_types_i.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Fri Jan 29 14:49:47 MST 2010
***/
public class SpaceTypesI_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <SpaceTypesI> meta = new SRecordMeta<SpaceTypesI>(SpaceTypesI.class, "space_types_i");

//Columns in table
   public static final SFieldInteger SpaceTypeId =
      new SFieldInteger(meta, "space_type_id",
         new SFieldFlags[] { SFieldFlags.SPRIMARY_KEY, SFieldFlags.SMANDATORY });

   public static final SFieldString SpaceTypeName =
      new SFieldString(meta, "space_type_name", 2147483647);

   public static final SFieldString SpaceTypeCode =
      new SFieldString(meta, "space_type_code", 2147483647);

   public static final SFieldDouble AgeRentDiscount =
      new SFieldDouble(meta, "age_rent_discount");

   public static final SFieldDouble DensityRentDiscount =
      new SFieldDouble(meta, "density_rent_discount");

   public static final SFieldDouble AgeMaintenanceCost =
      new SFieldDouble(meta, "age_maintenance_cost");

   public static final SFieldDouble AddTransitionConst =
      new SFieldDouble(meta, "add_transition_const");

   public static final SFieldDouble NewFromTransitionConst =
      new SFieldDouble(meta, "new_from_transition_const");

   public static final SFieldDouble NewToTransitionConst =
	      new SFieldDouble(meta, "new_to_transition_const");

   public static final SFieldDouble RenovateTransitionConst =
      new SFieldDouble(meta, "renovate_transition_const");
   
   public static final SFieldDouble RenovateDerelictTransitionConst =
	      new SFieldDouble(meta, "renovate_derelict_const");

   public static final SFieldDouble DemolishTransitionConst =
      new SFieldDouble(meta, "demolish_transition_const");

   public static final SFieldDouble DerelictTransitionConst =
      new SFieldDouble(meta, "derelict_transition_const");

   public static final SFieldDouble NoChangeTransitionConst =
      new SFieldDouble(meta, "no_change_transition_const");

   public static final SFieldDouble NewTypeDispersionParameter =
      new SFieldDouble(meta, "new_type_dispersion_parameter");

   public static final SFieldDouble GyDispersionParameter =
      new SFieldDouble(meta, "gy_dispersion_parameter");

   public static final SFieldDouble GzDispersionParameter =
      new SFieldDouble(meta, "gz_dispersion_parameter");

   public static final SFieldDouble GwDispersionParameter =
      new SFieldDouble(meta, "gw_dispersion_parameter");

   public static final SFieldDouble GkDispersionParameter =
      new SFieldDouble(meta, "gk_dispersion_parameter");

   public static final SFieldDouble NochangeDispersionParameter =
      new SFieldDouble(meta, "nochange_dispersion_parameter");

   public static final SFieldDouble IntensityDispersionParameter =
      new SFieldDouble(meta, "intensity_dispersion_parameter");

   public static final SFieldDouble MaintenanceCost =
      new SFieldDouble(meta, "maintenance_cost");

   public static final SFieldInteger SpaceTypeGroupId =
      new SFieldInteger(meta, "space_type_group_id");

   public static final SFieldDouble CostAdjustmentFactor =
      new SFieldDouble(meta, "cost_adjustment_factor");

   public static final SFieldDouble ConstructionCapacityTuningParameter =
      new SFieldDouble(meta, "construction_capacity_tuning_parameter");

   public static final SFieldDouble ConvertingFactorForSpaceTypeGroup =
      new SFieldDouble(meta, "converting_factor_for_space_type_group");

   public static final SFieldDouble MinIntensity =
	      new SFieldDouble(meta, "min_intensity");

   public static final SFieldDouble MaxIntensity =
	      new SFieldDouble(meta, "max_intensity");

//Column getters and setters
   public int get_SpaceTypeId(){ return getInt(SpaceTypeId);}
   public void set_SpaceTypeId( int value){setInt( SpaceTypeId,value);}

   public String get_SpaceTypeName(){ return getString(SpaceTypeName);}
   public void set_SpaceTypeName( String value){setString( SpaceTypeName,value);}

   public String get_SpaceTypeCode(){ return getString(SpaceTypeCode);}
   public void set_SpaceTypeCode( String value){setString( SpaceTypeCode,value);}

   public double get_AgeRentDiscount(){ return getDouble(AgeRentDiscount);}
   public void set_AgeRentDiscount( double value){setDouble( AgeRentDiscount,value);}

   public double get_DensityRentDiscount(){ return getDouble(DensityRentDiscount);}
   public void set_DensityRentDiscount( double value){setDouble( DensityRentDiscount,value);}

   public double get_AgeMaintenanceCost(){ return getDouble(AgeMaintenanceCost);}
   public void set_AgeMaintenanceCost( double value){setDouble( AgeMaintenanceCost,value);}

   public double get_AddTransitionConst(){ return getDouble(AddTransitionConst);}
   public void set_AddTransitionConst( double value){setDouble( AddTransitionConst,value);}

   public double get_NewFromTransitionConst(){ return getDouble(NewFromTransitionConst);}
   public void set_NewFromTransitionConst( double value){setDouble( NewFromTransitionConst,value);}

   public double get_NewToTransitionConst(){ return getDouble(NewToTransitionConst);}
   public void set_NewToTransitionConst( double value){setDouble( NewToTransitionConst,value);}

   public double get_RenovateTransitionConst(){ return getDouble(RenovateTransitionConst);}
   public void set_RenovateTransitionConst( double value){setDouble( RenovateTransitionConst,value);}
   
   public double get_RenovateDerelictTransitionConst(){ return getDouble(RenovateDerelictTransitionConst);}
   public void set_RenovateDerelictTransitionConst( double value){setDouble( RenovateDerelictTransitionConst,value);}
   
   public double get_DemolishTransitionConst(){ return getDouble(DemolishTransitionConst);}
   public void set_DemolishTransitionConst( double value){setDouble( DemolishTransitionConst,value);}

   public double get_DerelictTransitionConst(){ return getDouble(DerelictTransitionConst);}
   public void set_DerelictTransitionConst( double value){setDouble( DerelictTransitionConst,value);}

   public double get_NoChangeTransitionConst(){ return getDouble(NoChangeTransitionConst);}
   public void set_NoChangeTransitionConst( double value){setDouble( NoChangeTransitionConst,value);}

   public double get_NewTypeDispersionParameter(){ return getDouble(NewTypeDispersionParameter);}
   public void set_NewTypeDispersionParameter( double value){setDouble( NewTypeDispersionParameter,value);}

   public double get_GyDispersionParameter(){ return getDouble(GyDispersionParameter);}
   public void set_GyDispersionParameter( double value){setDouble( GyDispersionParameter,value);}

   public double get_GzDispersionParameter(){ return getDouble(GzDispersionParameter);}
   public void set_GzDispersionParameter( double value){setDouble( GzDispersionParameter,value);}

   public double get_GwDispersionParameter(){ return getDouble(GwDispersionParameter);}
   public void set_GwDispersionParameter( double value){setDouble( GwDispersionParameter,value);}

   public double get_GkDispersionParameter(){ return getDouble(GkDispersionParameter);}
   public void set_GkDispersionParameter( double value){setDouble( GkDispersionParameter,value);}

   public double get_NochangeDispersionParameter(){ return getDouble(NochangeDispersionParameter);}
   public void set_NochangeDispersionParameter( double value){setDouble( NochangeDispersionParameter,value);}

   public double get_IntensityDispersionParameter(){ return getDouble(IntensityDispersionParameter);}
   public void set_IntensityDispersionParameter( double value){setDouble( IntensityDispersionParameter,value);}

   public double get_MaintenanceCost(){ return getDouble(MaintenanceCost);}
   public void set_MaintenanceCost( double value){setDouble( MaintenanceCost,value);}

   public int get_SpaceTypeGroupId(){ return getInt(SpaceTypeGroupId);}
   public void set_SpaceTypeGroupId( int value){setInt( SpaceTypeGroupId,value);}

   public double get_CostAdjustmentFactor(){ return getDouble(CostAdjustmentFactor);}
   public void set_CostAdjustmentFactor( double value){setDouble( CostAdjustmentFactor,value);}

   public double get_ConstructionCapacityTuningParameter(){ return getDouble(ConstructionCapacityTuningParameter);}
   public void set_ConstructionCapacityTuningParameter( double value){setDouble( ConstructionCapacityTuningParameter,value);}

   public double get_ConvertingFactorForSpaceTypeGroup(){ return getDouble(ConvertingFactorForSpaceTypeGroup);}
   public void set_ConvertingFactorForSpaceTypeGroup( double value){setDouble( ConvertingFactorForSpaceTypeGroup,value);}
   
   public double get_MinIntensity(){ return getDouble(MinIntensity);}
   public void set_MinIntensity( double value){setDouble( MinIntensity,value);}
   
   public double get_MaxIntensity(){ return getDouble(MaxIntensity);}
   public void set_MaxIntensity( double value){setDouble( MaxIntensity,value);}
   
//Foreign key getters and setters
   public SpaceTypesGroup get_SPACE_TYPES_GROUP(SSessionJdbc ses){
     try{
/** Old code: 
        return SpaceTypesGroup.findOrCreate(get_SpaceTypeGroupId());
New code below :**/
        return ses.findOrCreate(SpaceTypesGroup.meta,new Object[]{ 
        	get_SpaceTypeGroupId(),
 });
     } catch (SException e) {
        if (e.getMessage().indexOf("Null Primary key") > 0) {
          return null;
        }
        throw e;
     }
   }
   public void set_SPACE_TYPES_GROUP( SpaceTypesGroup value){
      set_SpaceTypeGroupId( value.get_SpaceTypesGroupId());
   }

//Find and create
   public static SpaceTypesI findOrCreate( SSessionJdbc ses ,int _SpaceTypeId ){
      return ses.findOrCreate(meta, new Object[] {new Integer( _SpaceTypeId)});
   }
   public SRecordMeta <SpaceTypesI> getMeta() {
       return meta;
   }
}
