package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table transition_cost_codes.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class TransitionCostCodes extends TransitionCostCodes_gen implements java.io.Serializable {

}
