package com.hbaspecto.pecas.sd.orm;
import simpleorm.dataset.*;
import simpleorm.utils.*;
import simpleorm.sessionjdbc.SSessionJdbc;
import java.math.BigDecimal;
import java.util.Date;

/**	Base class of table transition_constants_i_view.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Fri Sep 25 16:13:29 MDT 2009
***/
abstract class TransitionConstantsIView_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <TransitionConstantsIView> meta = new SRecordMeta<TransitionConstantsIView>(TransitionConstantsIView.class, "transition_constants_i_view");

//Columns in table
   public static final SFieldString FromSpaceTypeName =
      new SFieldString(meta, "from_space_type_name", 2147483647);

   public static final SFieldString ToSpaceTypeName =
      new SFieldString(meta, "to_space_type_name", 2147483647);

   public static final SFieldDouble TransitionConstant =
      new SFieldDouble(meta, "transition_constant");

//Column getters and setters
   public String get_FromSpaceTypeName(){ return getString(FromSpaceTypeName);}
   public void set_FromSpaceTypeName( String value){setString( FromSpaceTypeName,value);}

   public String get_ToSpaceTypeName(){ return getString(ToSpaceTypeName);}
   public void set_ToSpaceTypeName( String value){setString( ToSpaceTypeName,value);}

   public double get_TransitionConstant(){ return getDouble(TransitionConstant);}
   public void set_TransitionConstant( double value){setDouble( TransitionConstant,value);}

//Find and create
   public static TransitionConstantsIView findOrCreate( SSessionJdbc ses  ){
      return ses.findOrCreate(meta, new Object[] {});
   }
   public SRecordMeta <TransitionConstantsIView> getMeta() {
       return meta;
   }
}
