package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table transition_costs.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class TransitionCosts extends TransitionCosts_gen implements java.io.Serializable {

}
