package com.hbaspecto.pecas.sd.orm;

/**Business rules class for table transition_constants_i.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class TransitionConstantsI extends TransitionConstantsI_gen implements java.io.Serializable {

}
