package com.hbaspecto.pecas.sd.orm;
import simpleorm.dataset.*;

import simpleorm.sessionjdbc.SSessionJdbc;
import com.hbaspecto.pecas.sd.ZoningRulesI;

/**	Base class of table zoning_rules_i.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Fri Sep 25 16:13:29 MDT 2009
***/
public abstract class ZoningRulesI_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <ZoningRulesI> meta = new SRecordMeta<ZoningRulesI>(ZoningRulesI.class, "zoning_rules_i");

//Columns in table
   public static final SFieldInteger ZoningRulesCode =
      new SFieldInteger(meta, "zoning_rules_code",
         new SFieldFlags[] { SFieldFlags.SPRIMARY_KEY, SFieldFlags.SMANDATORY });

   public static final SFieldString ZoningRulesCodeName =
      new SFieldString(meta, "zoning_rules_code_name", 2147483647);

   public static final SFieldBooleanBit NoChangePossibilities =
      new SFieldBooleanBit(meta, "no_change_possibilities");

   public static final SFieldBooleanBit DerelictionPossibilities =
      new SFieldBooleanBit(meta, "dereliction_possibilities");

   public static final SFieldBooleanBit DemolitionPossibilities =
      new SFieldBooleanBit(meta, "demolition_possibilities");

   public static final SFieldBooleanBit RenovationPossibilities =
      new SFieldBooleanBit(meta, "renovation_possibilities");

   public static final SFieldBooleanBit AdditionPossibilities =
      new SFieldBooleanBit(meta, "addition_possibilities");

   public static final SFieldBooleanBit NewDevelopmentPossibilities =
      new SFieldBooleanBit(meta, "new_development_possibilities");

//Column getters and setters
   public int get_ZoningRulesCode(){ return getInt(ZoningRulesCode);}
   public void set_ZoningRulesCode( int value){setInt( ZoningRulesCode,value);}

   public String get_ZoningRulesCodeName(){ return getString(ZoningRulesCodeName);}
   public void set_ZoningRulesCodeName( String value){setString( ZoningRulesCodeName,value);}

   public boolean get_NoChangePossibilities(){ return getBoolean(NoChangePossibilities);}
   public void set_NoChangePossibilities( boolean value){setBoolean( NoChangePossibilities,value);}

   public boolean get_DerelictionPossibilities(){ return getBoolean(DerelictionPossibilities);}
   public void set_DerelictionPossibilities( boolean value){setBoolean( DerelictionPossibilities,value);}

   public boolean get_DemolitionPossibilities(){ return getBoolean(DemolitionPossibilities);}
   public void set_DemolitionPossibilities( boolean value){setBoolean( DemolitionPossibilities,value);}

   public boolean get_RenovationPossibilities(){ return getBoolean(RenovationPossibilities);}
   public void set_RenovationPossibilities( boolean value){setBoolean( RenovationPossibilities,value);}

   public boolean get_AdditionPossibilities(){ return getBoolean(AdditionPossibilities);}
   public void set_AdditionPossibilities( boolean value){setBoolean( AdditionPossibilities,value);}

   public boolean get_NewDevelopmentPossibilities(){ return getBoolean(NewDevelopmentPossibilities);}
   public void set_NewDevelopmentPossibilities( boolean value){setBoolean( NewDevelopmentPossibilities,value);}

//Find and create
   public static ZoningRulesI findOrCreate( SSessionJdbc ses ,int _ZoningRulesCode ){
      return ses.findOrCreate(meta, new Object[] {new Integer( _ZoningRulesCode)});
   }
   public SRecordMeta <ZoningRulesI> getMeta() {
       return meta;
   }
}
