package com.hbaspecto.pecas.land;

import simpleorm.sessionjdbc.SSessionJdbc;

import com.hbaspecto.pecas.sd.orm.Parcels_gen;
import com.sun.swing.internal.plaf.metal.resources.metal;

/**Business rules class for table parcels.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class Parcels extends Parcels_gen implements java.io.Serializable, ParcelInterface {
	protected static long getMaximumPecasParcelNum(SSessionJdbc session){
		long maxNum = ((Long) session.rawQuerySingle("SELECT max(pecas_parcel_num) FROM parcels", false, new Object[0])).longValue();
		return maxNum;
	}
	
	protected static long getMinimumPecasParcelNum(SSessionJdbc session){
		long minNum = ((Long) session.rawQuerySingle("SELECT min(pecas_parcel_num) FROM parcels", false, new Object[0])).longValue();		
		return minNum;
	}
}
